#!/usr/bin/perl -w
# compress.pl - convert a compress.txt to a normal C file

use strict;

my $FILE;
my @word;
my $uncompress;

open (FILE, "compress.txt") or die "Couldn't open $FILE";

printf ("/* automatically generated by compress.pl */\n\
#include <compress.h>\n\
compress_type compress[] =\n{\n");

while (<FILE>)
  {
    (@word) = split;
    if (@word && 
	$word[0] ne '#' &&
	$word[0] ne '')
      {      
	printf ("  { \"%s\", ", $word[0]);
	
	# concatenate all other words to a string

	for (my $c = 1; $word[$c]; $c++)
	  {
	    printf ("%s ", $word[$c]);
	  }
	printf ("},\n");
      }
  }
close (FILE);

printf ("  { NULL, NULL }\n};\n");
