/* General defines, typedefs and protypes. This is -*- c++ -*- */
/* Copyright 1998-1999 Per Lundberg */

#ifndef __TANSTAAFL_H__
#define __TANSTAAFL_H__

#include "defs.h"
#include "fido.h"
#include "misc.h"

#include "msgbase.h"
#include "reader.h"
#include "tosser.h"
#include "scanner.h"
#include "mailer.h"
#include "maintenance.h"
#include "configuration.h"

#include "screen_linux.h"
#include "keyboard_linux.h"
#include "ui.h"
#include "window.h"
#include "dialog.h"

#include "config.h" /* config.h is generated by the configure script */

extern char *version, *program;
extern byte major, minor;
extern char **parameter;
extern word parameters;
extern char *program_name, *program_version;

enum 
{
  /* Message reader colors */
  
  READER_NORMAL = 0, READER_QUOTE, READER_KLUDGE, READER_ORIGIN, READER_HEADER,
  READER_PERSONAL,

  /* Message editor colors */
  
  EDITOR_NORMAL = 0x10, EDITOR_QUOTE, EDITOR_ORIGIN,

  /* Miscellaneous colors */

  MISC_STATUS = 0x20, MISC_WINDOW, MISC_TITLE, MISC_NORMAL, MISC_HIGHLIGHT,
  MISC_CHOSEN, MISC_BACKGROUND
};

/* The classes */

#ifdef __cplusplus

class TANSTAAFL
{
  READER reader;
  TOSSER tosser;
  SCANNER scanner;
  MAILER mailer;
  MAINTENANCE maint;
#ifdef __linux__
  bool ncurses;
#endif
  void intro (void);
  void help (void);
  void show_help (void);
  void done (void);

public:
  TANSTAAFL (int, char **);
  ~TANSTAAFL (void);
  void play (void);
};

extern CONFIG config;

#endif /* __cplusplus */
#endif /* __TANSTAAFL_H__ */
